# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7Z1V-mbfagsyd9uc6yFgf3bgVEHr8TW
"""

import requests

url = "https://restcountries.com/v3.1/all"
response = requests.get(url)
countries = response.json()

# Guardar el resultado en un archivo JSON
with open("countries.json", "w") as file:
    json.dump(countries, file, indent=4)